### ISSUE TITLE
predicting error

### ISSUE THREAD

**Issue by sunjiwon** [vxfung/MatDeepLearn#9]
Hello, 
I have a question about your framework matdeeplearn.
An error occurs when I predict the new material I synthesized!
Their target.csv file and csv file are in a folder...
I don't know why the error occurs..

Dataset used: StructureDataset(1017)
Traceback (most recent call last):
  File "main.py", line 552, in <module>
    main()
  File "main.py", line 238, in main
    print(dataset[0])
  File "/home/------/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 199, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/home/------/MatDeepLearn/matdeeplearn/process/process.py", line 702, in __call__
    data.y = data.y[0][self.index]
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by vxfung** [comment]
Hi sunjiwon, what does the csv file look like? Perhaps the setting for "target_index" in the config.yml is also incorrect?

**Comment by sunjiwon** [comment]
thanks for your answer and making this good method, I resolve this problem. your model has a very good prediction abilty:)
